[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra -p no:pytest_playwright --alluredir=reports/allure-results
markers =
    smoke: fast smoke tests
log_cli = true
log_cli_level = INFO
